volumes:
  pg_data:
  media:
  static:

services:
  db:
    container_name: foodgram-db
    image: postgres:15.14
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    build: ../backend/
    env_file: ../.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend/:/app/ # remove in prod
      - media:/app/media/
      - static:/static/
    depends_on:
      - db

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - static:/static/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - static:/static/
      - media:/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/static/api/docs/
    depends_on:
      - frontend
      - backend
